---
ip: 10.1.3.1
private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62396534633931376563636636663064346561383035633534646639646361623466373366666166
  6539313763613839626434393731326363653362346264340a333532396632353031383231376563
  35373464346635633166363835643761336466613464356363376131343938363937653366303731
  6333363065346236360a343233363432326165316166366537363932373232653863373662316566
  31353038643638353462306161613561353232626539626666373761303464323761666531656230
  3561626363383938386438363263343564306137613763323532
public_key: 6B1jfmkTHpI0ShMLD7lwrkU7pOmJIqfmT4jHUVfddDo=
