---
wg_template_name: mesh-peer
wg_address: 10.1.1.21
wg_endpoint: 192.168.42.21
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37353861363665363939393933656263356337616562373031353832336664323464343537333139
  3764373765323437336235376464323236383634373166310a346638653935353433613331323961
  66623362373963363465646132393333633366663737333766333830393038613831376338663261
  3838636230646531620a336132623938333264396239386138333133313564373862366633363564
  37666363333265363535633834333233346566396631663763363738356531396266353537376362
  6562376565373564393331623932323664336364623235656561
wg_public_key: D857ePjFlyh7Opmc32W8dQpnpH9s6wCjzf18ZhvMhzI=
