---
wg_address: 10.1.1.24
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64663336386438636134333132633131363539663462353663316133333939343034663230383232
  3036353664316366313839663636353833623561663333650a643338336634333263333230363133
  36313539666137386136646237396161623466653630653635633938663962616439313732373662
  3630393664343635610a653639663563653030373464663362386663303539316632316466366331
  38326539343061366665396665373734343935643166633266336634316634633337386135613635
  3339373632396661303365366233616364353333386630373764
wg_public_key: P3x3YNsY40yitKLZrd2Fobkgu4OkKm4GD1J5dxl5BV4=
