---
wg_address: 10.1.1.23
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31393564343264626466383165626166336433333566383131613934326465616563346362666433
  3934313162396363306465653735333232653039386132660a343733646261346230633633383962
  33343637333333346336633961383231653239356436383338343162396437373239636164363731
  3863376535643465650a636537376265653766333764303965313137396535386530623666643464
  34313565383463303361356165393431663933633362393430373061396337353464623537373237
  3961653135626466616532316661626535653066633966613435
wg_public_key: eASt9NdF9A2YJdCLpwT8Bu2Og6qNOzNlQxNj/gN1lX8=
