---
wg_template_name: mesh-peer
wg_address: 10.1.1.22
wg_endpoint: 192.168.42.22
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  63646234616138346437373937336362356535623639653330353066326432653066353163383464
  3737343637353838626532386634633536633566623836640a383233386336306565646534303764
  35333037353236623062333564363136353130376664313038313337393363633665353633383264
  3631383234623963390a616161313664616632373235343162663035396432323232376239653061
  63343034323639306431666461666564376166626465366332356131333937393530396633656435
  6335323332323731633330393330636432363234613437633739
wg_public_key: gVuCEWyHyKVrh1NjIZqcfVROWe68fnyk/p8mYozixEE=
