---
wg_template_name: edge-client
wg_address: 10.1.3.2
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  30626562636338666539306662363766653539643666633935653131373763333235333064333834
  6433633638626565386233356562363864363634656339390a386333613338326138323433636538
  34343638633564663931613531653964333464303961646438386362646339356262323936306138
  3361303734393836650a323631666339623635393536346263343861353264316561626135343636
  62656433623961343765613765393864646261323261393266643564386438653033326564346532
  6330333534333831663834343830386338333836613166386531
wg_public_key: fwevIlE7ZTraUpJg0mpjOtOKl0EfCefqsWuZFL1FbFM=
