---
ip: 10.1.3.3
private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  64303130633730393531386539313462643166333032336535613932333837663164316332353861
  6237396133373030613438336230303334323461666630350a333633353365653435386466316636
  31646537336263623231613631323863316434623438636364666638666364386233663436356331
  3065663463633762360a316234643765633565613235383336616266323361653362623461373761
  64333061383736333331313833336233333638643365313534373234666135323365623130363630
  3561343863616662383339626639626232393032613835316635
public_key: gBCSrXCdbIAL3l11Qast+yrbfnaOxUQLRpu9rXxnGBM=
