---
ip: 10.1.1.13
private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  37366531326637626531303565656662356561343562303534323730353861386566356261646235
  6134316562623764326261623736336238666262626532390a653535313166356637626662316334
  38646437613630636263346336396661373961386336633038336166306332613762646663663336
  3565353131623239310a643764373038316265323062356364666365343930336466303234383530
  31663764666163376136303837313863393437353431323534623363646235346137376264643061
  3939383534336638326562666439376664386661653266626438
public_key: 6USqrGKmlq1V869eGKtp2Mjt5aRqlCh9cFCHoqLkrCc=
