---
wg_template_name: mesh-peer
wg_address: 10.1.1.11
wg_endpoint: 192.168.42.11
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  32376136373637323238366261616135356537393566323234646536303162376235623163626130
  3731646637643836646366666361303830373963303661370a303863623634363331306131383264
  62386637353261333037326464653038666466653361623834626536323961313834616332363839
  3962393861326461640a653438613065343265633235383638346337663963393032323131633436
  36353530643863333163306230303732336235316434306631306131656134316361383234373566
  3265316563356630633435303964343630633731646532313639
wg_public_key: 5SjTrnOrB7h0dZdUP63AO4gbkWNRSFF7QcTqp99iqk0=
