---
wg_address: 10.1.1.12
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  61663835343731643636616434356566313366383737663366666239336164373735623438643533
  3163383931346339666364633565656562323166656431320a343466373135326432663838356466
  31373835313130646439623166336336643937386230376133363465646233383632643836656637
  3766323031616633360a343963373835646464396132666639643830626164656636356330373939
  62616261346433653761333033343230613731383637613263366531393734306434656638613063
  3336343131346262343133636666363232636530353162303531
wg_public_key: hE1W+m77d+K+3ELdrTY1S9Gcy2eIxRkqzLWm+S8swFg=
