---
wg_address: 10.1.2.1
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34393363323563343230623139663937386533336136386637303765396563626666653138313035
  6233636135663435306134326466303265636432633630620a363762363639613334646135663937
  64663466636262663666326434326663633738383834666634663435363565653330316337346333
  3138653631313734340a666331363934313965386163303930646530303533346436393563373333
  34333230353061306264383938303235393331336361333932363036356562373335626633363632
  3133633266656139353036386333613438643838346132393765
wg_public_key: X+SzgpLiefHtwvqvEKiI3ST70+CgoYEecsSyvow2WEw=
