---
wg_address: 10.1.3.4
wg_private_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31316266613638633561626236646635313265633234623434636631656433396533636130623731
  3338666166356535646261376536333231373237323037340a306238343136396633616432333361
  35393539316238636537626230336165663830353233656439386234636663336631663361333663
  6233313137626430360a653463376365333436353639626263383835353831666536386463396265
  31373063613966326265383766656562313532613335636365363132626266353162303765636631
  3031393836346631646236663033343434396539623666613663
wg_public_key: RTuSndzIdlU7Es93q2q6eY67RxU9iFdP2aT7qPtJlAk=
