---
- name: Provision
  hosts: all
  tasks:
    - name: Build peer config
      become: true
      ansible.builtin.template:
        src: templates/{{ wg_template_name }}.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: '0600'
      notify:
        - Restart wireguard

    - name: Ensure WireGuard interface is enabled and running
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: true
        state: started

  handlers:
    - name: Restart wireguard
      ansible.builtin.systemd:
        name: wg-quick@wg0
        state: restarted
